export enum ProblemCode {
  VALIDATION,
    USER_NOT_FOUND,
    LIST_ALREADY_EXISTS,
    LIST_NOT_FOUND,
    UNAUTHORIZED,
    COMIC_NOT_FOUND,
    COMIC_ALREADY_IN_LIST,
    USER_ALREADY_EXISTS,
    COMIC_QUANTITY_UNAVAIABLE,
    COMIC_ALREADY_IN_CART,
    COMIC_NOT_FOUND_IN_CART
}
